openapi: 3.0.0
info:
  title: Role Management API
  version: 1.0.0
  description: API documentation for managing roles, including CRUD operations and restore functionality.

tags:
  - name: Roles
    description: Role management endpoints

paths:
  /roles:
    get:
      tags: [Roles]
      summary: List all roles
      responses:
        200:
          description: List of roles
    post:
      tags: [Roles]
      summary: Create a new role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Role'
      responses:
        201:
          description: Role created

  /roles/{id}:
    get:
      tags: [Roles]
      summary: Get role by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Role found
        404:
          description: Role not found
    put:
      tags: [Roles]
      summary: Update role by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Role'
      responses:
        200:
          description: Role updated
    delete:
      tags: [Roles]
      summary: Soft delete a role
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Role deleted

  /roles/{id}/restore:
    post:
      tags: [Roles]
      summary: Restore a deleted role
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Role restored

components:
  schemas:
    Role:
      type: object
      required:
        - code
        - translations
      properties:
        code:
          type: string
        translations:
          type: array
          items:
            type: object
            required: [language_code, name]
            properties:
              language_code:
                type: string
              name:
                type: string
              description:
                type: string