version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ipcms_db
      MYSQL_USER: ipcms_user
      MYSQL_PASSWORD: ipcms_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  ip-web:
    build: ./
    container_name: ip-web
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
